"""
==========================================================
Export Utilities
==========================================================
"""

from io import BytesIO
import pandas as pd

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

from reportlab.lib.styles import getSampleStyleSheet


# --------------------------------------------------------
# CSV
# --------------------------------------------------------

def export_csv(df):

    return df.to_csv(
        index=False
    ).encode("utf-8")


# --------------------------------------------------------
# Excel
# --------------------------------------------------------

def export_excel(df):

    output = BytesIO()

    with pd.ExcelWriter(
        output,
        engine="openpyxl"
    ) as writer:

        df.to_excel(
            writer,
            index=False,
            sheet_name="Crime Data"
        )

    return output.getvalue()


# --------------------------------------------------------
# PDF
# --------------------------------------------------------

def export_pdf(metrics):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "<b>Chicago Crime Analytics Report</b>",
            styles["Title"],
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"Total Crimes : {metrics['total_crimes']:,}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"Arrest Rate : {metrics['arrest_rate']:.2f}%",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"Crime Categories : {metrics['crime_categories']}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"Districts : {metrics['districts']}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"Top Crime : {metrics['top_crime']}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"Top Crime Count : {metrics['top_crime_count']}",
            styles["BodyText"],
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf


# --------------------------------------------------------
# Summary
# --------------------------------------------------------

def export_summary(metrics):

    summary = f"""
Chicago Crime Analytics Summary

================================

Total Crimes :
{metrics['total_crimes']:,}

Arrest Rate :
{metrics['arrest_rate']:.2f}%

Crime Categories :
{metrics['crime_categories']}

Districts :
{metrics['districts']}

Top Crime :
{metrics['top_crime']}

Top Crime Count :
{metrics['top_crime_count']}

Generated by

Chicago Crime Analytics Dashboard
"""

    return summary.encode("utf-8")